### ISSUE TITLE
Arabic OCR

### ISSUE THREAD

**Issue by chomskynet** [OCR4all/ocr4all_models#1]
kindly be informed that I need to test Arabic OCR in ocr4all please send to me the steps to can I do 
thanks

**Comment by maxnth** [comment]
If you haven't already set up OCR4all on your machine/server, you can use our setup guides for [Docker](https://github.com/OCR4all/getting_started/blob/master/ocr4all-setup_guide.pdf) or [VirtualBox](https://github.com/OCR4all/getting_started/blob/master/ocr4all-setup_guide_virtualbox_eng.pdf).
In case you already set up OCR4all all you need to do is follow the OCR4all workflow (for additional help/information take a look at our [user guide](https://github.com/OCR4all/getting_started/blob/master/ocr4all-user_guide_eng.pdf) and/or ask us) and use a model trained with [calamari](https://github.com/Calamari-OCR/calamari) on Arabic data. 
In case you don't already have such a model you can train it yourself with OCR4all.

In case something is unclear or not working as intended, feel free to contact us.

**Comment by maxnth** [comment]
I assume that this is solved. Otherwise please reopen the issue.
