### ISSUE TITLE
Other models available?

### ISSUE THREAD

**Issue by khe29** [OCR4all/ocr4all_models#2]
Are there other models for modern fonts available for the use with OCR4all?

**Comment by hannesa2** [comment]
eg https://en.wikipedia.org/wiki/Kurrent ?

**Comment by maxnth** [comment]
All models trained and / or recommended by us will be published [here](https://github.com/Calamari-OCR/calamari_models_experimental) or [here](https://github.com/Calamari-OCR/calamari_models)

**Comment by MonikaBarget** [comment]
I am also confused about the model world within OCR4all. When I look at the model selection in the tool itself, I see many more models, but often I cannot make sense of them just based on the names. I would also love to have a full overview of all OCR4all models available, maybe not just those trained by @maxnth and his team?

I think the eScriptorium community is using Zenodo to publish their pre-trained models for everyone to reuse. Does something similar exist for OCR4all, or could it be set up?

I have used OCR4all for 18th-century fraktur so far but would now also like to experiment with early 20th-century administrative forms, which partly contain handwritten content as well.
