### ISSUE TITLE
meta-data

### ISSUE THREAD

**Issue by bertsky** [OCR4all/ocr4all_models#3]
Could you please provide some more information on the published model files (where available)?

- training material
- evaluation material / results
- input format/workflow dependencies (raw/bin, normalization/dewarping/deskewing)
- output text characteristics (canonicalization/normalization, special characters for line/paragraph separators or quotes etc)

**Comment by maxnth** [comment]
I'm just stumbling across this issue so it's probably not relevant anymore but all models which are contained in this repo are sourced from [here](https://github.com/Calamari-OCR/calamari_models_experimental) or [here](https://github.com/Calamari-OCR/calamari_models) and it looks like their respective README now contains some information about the models.
